### PR TITLE
Popup window

### PR DESCRIPTION
**Pull request by shuhad786**

### CODE REVIEW

**Review by Kandy-Peter — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Shuhad786  
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has some issues needed to be fixed before reviewing it:
- [ ] Make sure to give your PR a meaningful description, so it will look professional like it is described in this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏
---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by RolandM99 — COMMENTED** [review]
Hi @Shuhad786, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

- [ ] As requested by the previous reviewer, make sure that your PR has a  descriptive title telling you what changes are inside and also a short summary describing introduced changes in more detail.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by cwaku — COMMENTED** [review]
Hi @Shuhad786 and @ManarOmari 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with no PR description. To make sure it looks professional, kindly add a meaningful description to your PR like it is described in this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by shuhad786** [comment]
Closed pull request as per reviewer instructions

**Pull request closed without merging**
